sudo: required
language: bash
services:
  - docker

script:
  - docker build -t $DOCKER_REGISTRY/azured/multi-script:$TRAVIS_BUILD_NUMBER .
  - docker login "$DOCKER_REGISTRY" -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker tag $DOCKER_REGISTRY/azured/multi-script:$TRAVIS_BUILD_NUMBER $DOCKER_REGISTRY/azured/multi-script
  - docker push $DOCKER_REGISTRY/azured/multi-script
