sudo: required

services:
  - docker

before_install:
  - ls 
  - docker build -t azured/multi-script .
  - docker login "$DOCKER_REGISTRY" -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push $DOCKER_REGISTRY/azured/multi-script
